### ISSUE TITLE
[request] support execution from non-undercloud host

### ISSUE THREAD

**Issue by bregman-arie** [zahlabut/LogTool#1]
I think there are very useful scripts here but as someone who switches between clouds all the time, it could be very useful for me to execute this from my laptop and every time connect the undercloud and install it there.

**Comment by zahlabut** [comment]
Hi Arie!

I think that it's possible to add such an option. So, once you having
LogTool installed on your laptop, you'll need to provide these details per
cloud (per Undercloud host):
 1. IP to SSH
 2. SSH user
 3. SSH password or key
 4. Path ro stacrc file
 5. Time Since (export unique errors occurred after this time)
to make it happen.

LogTool will use SSH to connect to each one of configured cloud (in parallel) and to bring
you all result files from each Undercloud to your Laptop.
Make sense?

Thanks!

**Comment by bregman-arie** [comment]
That's a lot of information to provide per cloud...Isn't the information we already store in /etc/openstack/clouds.yml is enough? for things like "path to stackrc" a default can be used and if needed, a user can override the default

**Comment by zahlabut** [comment]
Functionality you are looking for is already implemented. 
Not a bug.
